## Bag of Words
#### 1. CountVectorizr

In [80]:
text = 'My wife likes to watch baseball games and my daughter likes to watch baseball games too'

In [81]:
from sklearn.feature_extraction.text import CountVectorizer

cvect = CountVectorizer()
cvect.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.int64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': None,
 'min_df': 1,
 'ngram_range': (1, 1),
 'preprocessor': None,
 'stop_words': None,
 'strip_accents': None,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'vocabulary': None}

In [82]:
output = cvect.fit_transform([text])
output.toarray()

array([[1, 2, 1, 2, 2, 2, 2, 1, 2, 1]], dtype=int64)

- 불용어(Stopwords) 처리

In [83]:
# 직접 지정
my_stopwords = ['my', 'to', 'and']
cvect = CountVectorizer(stop_words=my_stopwords)
print(cvect.fit_transform([text]).toarray())
print(cvect.vocabulary_)

[[2 1 2 2 1 2 1]]
{'wife': 6, 'likes': 3, 'watch': 5, 'baseball': 0, 'games': 2, 'daughter': 1, 'too': 4}


In [84]:
# NLTK에서 제공하는 불용어 사용
from nltk.corpus import stopwords

sw = stopwords.words('english')
cvect = CountVectorizer(stop_words=sw)
print(cvect.fit_transform([text]).toarray())
print(cvect.vocabulary_)

[[2 1 2 2 2 1]]
{'wife': 5, 'likes': 3, 'watch': 4, 'baseball': 0, 'games': 2, 'daughter': 1}


In [85]:
# Scikit-Learn에서 제공하는 불용어 사용
cvect = CountVectorizer(stop_words='english')
print(cvect.fit_transform([text]).toarray())
print(cvect.vocabulary_)

[[2 1 2 2 2 1]]
{'wife': 5, 'likes': 3, 'watch': 4, 'baseball': 0, 'games': 2, 'daughter': 1}


- 인덱스에 해당하는 단어를 알려주는 함수

In [86]:
voca = cvect.vocabulary_
for key, value in voca.items():
    print(key, value)

wife 5
likes 3
watch 4
baseball 0
games 2
daughter 1


In [87]:
def get_word(index, voca):
    for key, value in voca.items():
        if index == value:
            return key

get_word(4, cvect.vocabulary_)

'watch'

#### 2. TF-IDF(Term Frequeny - Inverse Document Frequency) Vectorizer

In [88]:
text = ['My wife likes to watch baseball games and my daughter likes to watch baseball games too',
        'My wife likes to play baseball.']

In [89]:
from sklearn.feature_extraction.text import TfidfVectorizer

tvect = TfidfVectorizer(stop_words='english')
tvect.fit_transform(text).toarray()

array([[0.38649245, 0.27160082, 0.54320165, 0.38649245, 0.        ,
        0.54320165, 0.19324622],
       [0.44832087, 0.        , 0.        , 0.44832087, 0.63009934,
        0.        , 0.44832087]])

In [90]:
print(tvect.vocabulary_)

{'wife': 6, 'likes': 3, 'watch': 5, 'baseball': 0, 'games': 2, 'daughter': 1, 'play': 4}


In [91]:
cevct = CountVectorizer(stop_words='english')
cvect.fit_transform(text).toarray()

array([[2, 1, 2, 2, 0, 2, 1],
       [1, 0, 0, 1, 1, 0, 1]], dtype=int64)

### 3. N-gram

In [92]:
text = ['Machine learning is fun and not boring.',
        'Machine is boring and learning is not fun.']

In [93]:
cvect = CountVectorizer(stop_words='english')
cvect.fit_transform(text).toarray()     # 차이가 없다.

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

In [95]:
cvect = CountVectorizer(stop_words='english', ngram_range=(1,2))
cvect.fit_transform(text).toarray()

array([[1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 1, 1, 0, 1, 1, 1, 1, 0]], dtype=int64)

In [96]:
cvect.vocabulary_

{'machine': 6,
 'learning': 4,
 'fun': 2,
 'boring': 0,
 'machine learning': 8,
 'learning fun': 5,
 'fun boring': 3,
 'machine boring': 7,
 'boring learning': 1}

### 4. Hyper Parameter

In [97]:
tvect.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.float64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': None,
 'min_df': 1,
 'ngram_range': (1, 1),
 'norm': 'l2',
 'preprocessor': None,
 'smooth_idf': True,
 'stop_words': 'english',
 'strip_accents': None,
 'sublinear_tf': False,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'use_idf': True,
 'vocabulary': None}